apiVersion: v1
kind: Pod
metadata:
  name: run-reporter
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:v3.13.1
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: daily-production-inventory
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      value: 2022-04-28T08:14:36Z
    - name: TIGERA_COMPLIANCE_REPORT_END_TIME
      value: 2022-04-28T08:20:36Z
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: LOG_LEVEL
      value: "warning"
    - name: ELASTIC_INDEX_SUFFIX
      value: cluster
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/ssl/elastic/ca.pem
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
  volumes:
  - name: var-log-calico 
    hostPath:
      path: /var/log/calico
      type: DirectoryOrCreate
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tls.crt
        path: ca.pem
      secretName: tigera-secure-es-gateway-http-certs-public

