apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: daily-cis-results
spec:
  reportType: cis-benchmark
  schedule: 15 9 * * *
  cis:
    highThreshold: 100
    medThreshold: 50
    includeUnscoredTests: true
    numFailedTests: 5
    resultsFilters:
    - benchmarkSelection: { kubernetesVersion: "1.21" }
      exclude: ["1.1.4", "1.2.5"]
