apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: quarantine
spec:
  order: 175

---

apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: platform
spec:
  order: 200

---

apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: security
spec:
  order: 250
